name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test -- --watchAll=false
    
    - name: Build package
      run: npm run build
    
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          ## Changes in this Release
          
          - See [CHANGELOG.md](CHANGELOG.md) for detailed changes
          
          ## Installation
          
          ```bash
          npm install liquid-glass@${{ github.ref_name }}
          ```
          
          ## Documentation
          
          - [GitHub Repository](https://github.com/yourusername/liquid-glass)
          - [NPM Package](https://www.npmjs.com/package/liquid-glass)
    
    - name: Build and Deploy Storybook
      run: |
        npm run build-storybook
        # Add your Storybook deployment commands here
      env:
        STORYBOOK_DEPLOY_TOKEN: ${{ secrets.STORYBOOK_DEPLOY_TOKEN }}